name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1


    - name: Print ECR Login Output
      run: |
        echo "ECR Registry URL: ${{ steps.login-ecr.outputs.registry }}"

    - name: Build, tag, and push image to Amazon ECR
      run: |
        ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY=${{ secrets.AWS_ECR_REPOSITORY }}
        IMAGE_TAG=latest
        IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

        echo "Building image with tag: $IMAGE_URI"
        docker build -t $IMAGE_URI .
        
        echo "Pushing image to ECR"
        docker push $IMAGE_URI
        if [ $? -eq 0 ]; then
          echo "Docker push succeeded"
        else
          echo "Docker push failed"
          exit 1
        fi

    - name: Update Lambda function
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: YOUR_LAMBDA_FUNCTION_NAME  # Replace with your Lambda function name
        image_uri: "${{ secrets.AWS_ECR_REPOSITORY }}:latest"
