name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
      # Define IMAGE_URI at the job level
      IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPOSITORY }}:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Enable debug mode for Docker daemon
    - name: Enable Docker debug mode
      run: |
        echo '{"debug": true}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-2

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t $IMAGE_URI .
        echo "Pushing image to ECR: $IMAGE_URI"
        docker push $IMAGE_URI
        if [ $? -eq 0 ]; then
          echo "Docker push succeeded"
        else
          echo "Docker push failed"
          exit 1
        fi
      env:
        AWS_REGION: us-east-2
        IMAGE_URI: ${{ env.IMAGE_URI }} # Reference the job-level variable

    - name: Update Lambda function
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-2
        function_name: github_docker_test
        image_uri: ${{ env.IMAGE_URI }} # Reference the job-level variable


